version: '3.8'

services:
  frontend:
    build:
      context: ./frontend-app
      dockerfile: Dockerfile
    ports:
      - "3000:80" # Cambiamos a 3000 para que coincida con tu puerto de entrega de Tailscale
    depends_on:
      - backend

  backend:
    image: node:18-alpine # Usamos una imagen oficial directa para no necesitar un Dockerfile interno
    working_dir: /app
    volumes:
      - ./herramientas-node-api:/app
    command: sh -c "npm install && npm start" # Instala dependencias y arranca la API automáticamente
    environment:
      - DB_PASSWORD=${DB_PASSWORD}
      - JWT_SECRET=${JWT_SECRET}
    # Se mantiene interno dentro de la red de Docker sin exponerse directamente
