version: '3.8'

services:
  frontend:
    build:
      context: ./frontend-app
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - backend

  backend:
    build:
      context: ./herramientas-node-api
      dockerfile: Dockerfile # O la configuración de docker que maneje su API
    environment:
      - DB_PASSWORD=${DB_PASSWORD}
      - JWT_SECRET=${JWT_SECRET}
    # No exponemos el puerto del backend al público, se queda interno