version: '3.8'

services:
  frontend:
    build:
      context: ./frontend-app
      dockerfile: Dockerfile
    ports:
      - "3000:5173"
    depends_on:
      - backend

  backend:
    build:
      context: ./herramientas-node-api
      dockerfile: Dockerfile
    ports:
      - "5000:3000"  # Mapea el puerto 5000 de Docker al puerto 3000 interno de Node
    environment:
      - DB_PASSWORD=${DB_PASSWORD}
      - JWT_SECRET=${JWT_SECRET}
